/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DialogContainer: typeof import('./src/components/dialog-custom/DialogContainer.vue')['default']
    DialogCustom: typeof import('./src/components/dialog-custom/index.vue')['default']
    DialogTitle: typeof import('./src/components/dialog-custom/DialogTitle.vue')['default']
    DidlogBodyTitle: typeof import('./src/components/dialog-custom/DidlogBodyTitle.vue')['default']
    DidlogContainer: typeof import('./src/components/dialog-custom/DidlogContainer.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeleInput: typeof import('./src/components/kele-input/index.vue')['default']
    KeleTab: typeof import('./src/components/kele-tabs/KeleTab.vue')['default']
    KeleTabs: typeof import('./src/components/kele-tabs/KeleTabs.vue')['default']
    PageTab: typeof import('./src/components/kele-tabs/PageTab.vue')['default']
    PageTabs: typeof import('./src/components/kele-tabs/PageTabs.vue')['default']
    PopoverSelect: typeof import('./src/components/popover-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanDialog: typeof import('vant/es')['Dialog']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlady: typeof import('vant/es')['Overlady']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
